spring:
  datasource:
    sqlScriptEncoding: UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3?characterEncoding=UTF-8
    username: root
    password: passw0rd
  # アプリケーション起動時にデータベースを初期化しないようにする
  jpa:
    hibernate:
      ddl-auto: update
    # spring boot起動時にDBにテーブル作成できない問題の対応
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
logging:
  level:
    sql: debug